.TH ZUU 1 "Wednesday January 26 2024" "8.0.1" "Zuu User Manual"
.SH SYNOPSIS
.B zuu
\fB\fROPTIONS\fR
.SH DESCRIPTION
A program to check your code before all commit with your favorite versioning system.
.TP
It's support \fBgit\fR and \fBmercurial\fR.
.SH OPTIONS
.TP
.BR init 
Init code tracking.
.TP
.BR badges
Run the hook and generate all badges.
.TP
.BR update
Erase the hook file to the latest content.
.SS WATCH MODE
\fB--watch \fR[ WAITING_TIME ]\fR
.TP
.BR
Run hook in watch mode.
.SS WAITING_TIME
.TP
The sleep time to re run the script in seconds.
.TP
The default \fBWAITING_TIME\fR value is set to \fBone minute\fR by default.
.TP
If the \fBWAITING_TIME\fR is set waiting this time.
.SS EXIT WATCH MODE
.TP
.BR 
Ctrl+c to exit.
.SH EXIT STATUS 
.TP
.BR 0 "
Code is valid
.TP
.BR 1 "
Code not valid
.SH AUTHORS
.TP
Micieli Willy <micieli@vivaldi.net> 
.SH GET A COPY
.TP
git clone https://github.com/taishingi/zuu
.SH REPORTING BUGS
.TP
.BR \fRhttps://github.com/taishingi/zuu/issues\fR
.SH COPYRIGHT
.PP
Copyright © 2023 Free Software Foundation, Inc.  License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.TP
This  is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
\fBgit\fR(1) \fBhg\fR(1)\fR

