[package]
name = "zuu"
version = "0.4.2"
edition = "2021"
description = "A tests runner for rust"
license-file = "LICENSE"
repository = "https://github.com/taishingi/zuu"
readme = "README.md"
authors = ["Willy Micieli"]

[[bin]]
name = "zuu"
path = "bin/zuu/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rsbadges = "1.1.5"
