[package]
name = "zuu"
version = "7.0.0"
edition = "2021"
license-file = "LICENSE"
keywords = ["clippy", "git", "hook"]
categories = ["development-tools"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/taishingi/zuu"
description = "A program to run tests before commit"
