[package]
name = "zuu"
version = "0.3.6"
edition = "2021"
description = "A tests runner for rust"
license = "GPL-2.0-or-later"
repository = "https://github.com/taishingi/zuu"

[[bin]]
name = "zuu"
path = "bin/zuu/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
glob = "0.3.1"
rsbadges = "1.1.5"
crossterm_cursor = "0.4.0"
