#!/bin/bash

cd /tmp

if [ $? -ne 0 ]
then
	exit 1
else
	echo "Switching of directory..."
	rm -rf oh
fi

git clone https://github.com/shingitai/yubel oh

cd oh && cmake . && sudo make install

cd /tmp

rm -rf oh

exit $?
