#!/usr/bin/bash

unset GIT_DIR
NOCOLOR='\033[0m'
RED='\033[1;31m'
GREEN='\033[1;32m'
WHITE='\033[1;37m'

FORMAT=false
VERIFY=false
AUDIT=false
CLIPPY=false
TESTS=false
CHECK=false


if ! cargo verify-project --quiet  > verify.out 2> verify_error.out
then
    ${EDITOR} verify.out verify_error.out
    VERIFY=false
else
    VERIFY=true
fi

if ! cargo fmt --check  > fmt.out 2> fmt_error.out
then
    ${EDITOR} fmt.out fmt_error.out
    FORMAT=false
else
    FORMAT=true
fi


if ! cargo audit --quiet  > audit.out 2> audit_error.out
then
    ${EDITOR} audit.out audit_error.out
    AUDIT=false
else
    AUDIT=true
fi

if ! cargo clippy --quiet -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo > clippy.out 2> clippy_error.out
then
    ${EDITOR} clippy.out clippy_error.out
    CLIPPY=false
else
    CLIPPY=true
fi

if ! cargo test --quiet --tests --all-targets --no-fail-fast  > tests.out 2> test_error.out
then
    ${EDITOR} tests.out test_error.out
    TESTS=false
else
    TESTS=true
fi

if ! cargo check --quiet --all-targets  > check.out 2> check_error.out
then
    ${EDITOR} check.out check_error.out
    CHECK=false
else
    CHECK=true
fi


clear


if [ $VERIFY == true ]
then
    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] verify${NOCOLOR}"
else
    echo -e "\n${WHITE}[${RED} KO${WHITE} ] verify${NOCOLOR}"
fi

if [ $FORMAT == true ]
then
    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] format${NOCOLOR}"
else
    echo -e "\n${WHITE}[${RED} KO${WHITE} ] format${NOCOLOR}"
fi


if [ $AUDIT == true ]
then
    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] audit${NOCOLOR}"
else
    echo -e "\n${WHITE}[${RED} KO${WHITE} ] audit${NOCOLOR}"
fi

if [ $CLIPPY == true ]
then
    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] clippy${NOCOLOR}"
else
    echo -e "\n${WHITE}[${RED} KO${WHITE} ] clippy${NOCOLOR}"
fi

if [ $TESTS == true ]
then
    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] tests${NOCOLOR}"
else
    echo -e "\n${WHITE}[${RED} KO${WHITE} ] tests${NOCOLOR}"
fi

if [ $CHECK == true ]
then
    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] check${NOCOLOR}"
else
    echo -e "\n${WHITE}[${RED} KO${WHITE} ] check${NOCOLOR}"
fi

if test $CLIPPY && $TESTS && $CHECK && $AUDIT && $VERIFY && $FORMAT
then
    echo -e "\n${WHITE}[${GREEN} OK${WHITE} ] Code is valid${NOCOLOR}\n"
    exit 0
else
    echo
    exit 1
fi