#!/bin/bash

tput init
tput bold
tput cup  0
printf "\033[?25l"
cols=`tput cols`
run_unit()
{
    tput clear
    for i in `find  ./specs/units/   -type f -name "zuu_*.cpp"`
    do
	g++ $i -l Unit -l Fs -o zzz && ./zzz && rm ./zzz
    done
    _bar "Units"
}


loop_install()
{

	while [ true ]
	do
		install
	done
}

_()
{

    tput cup  0 $1 
    printf "$2"
    sleep 1
}

_bar()
{
	sleep 7
	tput clear
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 000 \033[1;34m]"
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 001 \033[1;34m]"
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 010 \033[1;34m]"
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 011 \033[1;34m]"
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 100 \033[1;34m]"
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 101 \033[1;34m]"
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 110 \033[1;34m]"
	_ 0  "\033[1;34m[ \033[1;36m$1\033[1;34m ]-[\033[1;32m 111 \033[1;34m]\n\n"
}	
main()
{
	echo -e -n  "\033[1;36mEntrer le chemin du projet à tester : \033[1;32m" 

	read p
	while [ ! -d  "${HOME}/${p}/specs" ]
	do
		echo -e -n  "\033[1;36mEntrer le chemin du projet à tester : \033[1;32m" 
		read p
	done	
	
	tput clear
	cd "${HOME}/${p}"
	printf "[ ~/$p ]\n\033[1;34m1) Executer les tests unitaires\n2) Quitter le programme\n"
	

	echo -e -n "\033[1;36mVoitre choix : \033[1;32m" 
	read choice

	if [ -z  $choice ]
	then
		tput clear
		main
	elif [ $choice == "1" ]
	then
	    while [ true ]
	    do
		run_unit
 	    done
        else
            printf "\033[?25h"
	    exit 1	
	fi	
}

main
