name: continuous
on:
  push:
    branches: [ "master" , "develop" ]
  pull_request:
    branches: [ "master" , "develop"]
env:
  CARGO_TERM_COLOR: always
jobs:
  continuous:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deps 
      run: sudo apt-get install -y curl fd-find git docker-ce docker-ce-cli containerd.io packer && packer plugins install github.com/hashicorp/docker
    - name: continuous
      run: git clone https://github.com/taishingi/continuous-template.git continuous && cd continuous/rust && ./scripts-gen "github.com" "taishingi" "zuu" "${GITHUB_REF##*/}" "4" && packer validate . && packer build .
