name: zuu

on:
  push:
    branches: [ "master" , "develop" ]
  pull_request:
    branches: [ "master" , "develop"  ]

env:
  CARGO_TERM_COLOR: always
  TERM: xterm-256color
jobs:
  zuu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: zuu
      run: bash pre-commit
